name: GraalVM Native Image builds
on: [release]
jobs:
  build:
    permissions: write-all
    name: HelloWorld on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: "21"
          distribution: "graalvm"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: "true"

      - name: Build and run HelloWorld.java
        run: |
          echo 'public class HelloWorld { public static void main(String[] args) { System.out.println("Hello, World!"); } }' > HelloWorld.java
          javac HelloWorld.java
          native-image HelloWorld
          ./helloworld

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: helloworld-${{ matrix.os }}
          path: helloworld*

      - name: Rename Files
        if: runner.os == 'Linux' || runner.os == 'macOS' 
        run: mv helloworld helloworld-${{ matrix.os }}

      - name: List Files
        if: runner.os == 'Linux' || runner.os == 'macOS' 
        run: ls -l

      - name: List Files
        if: runner.os == 'Windows'
        run: dir

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') && (runner.os == 'Linux' || runner.os == 'macOS' )
        with:
          files: helloworld-${{ matrix.os }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') && runner.os == 'Windows'
        with:
          files: helloworld-${{ matrix.os }}.exe
